import Category from "@/commonTypes/commonTypes";
import Avatar from "@/components/homePage/Avatar/Avatar";
import CategoryNav from "@/components/homePage/CategoryNav/CategoryNav";
import Drawar from "@/components/homePage/Drawar/Drawar";
import NavDrawar from "@/components/homePage/NavDrawar/NavDrawar";
import Navbar from "@/components/homePage/Navbar/Navbar";
import SeachBar from "@/components/homePage/SearchBar/SeachBar";
import axios from "axios";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await axios.get("https://idr-foundation-job-task-server.vercel.app/");
  const categorys: Category[] = res.data.categorys;
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "#EBEEF2" }}>
        <div className="flex lg:hidden justify-between items-center w-[90%] mx-auto mt-6">
          <h1 className="text-2xl">{"< Dua Page"}</h1>
          <Drawar />
        </div>
        <div className="flex lg:hidden items-center w-[90%] mx-auto mt-6 bg-white p-3 rounded-xl">
          <NavDrawar data={categorys} />
          <h1 className="text-2xl mx-auto">Menu</h1>
        </div>

        <div className="flex w-[90%] lg:w-full mx-auto">
          <div className="lg:w-[10%] w-0">
            <Navbar />
          </div>
          <div className="mt-5 lg:mx-8 w-full">
            <div className="lg:flex justify-between hidden ">
              <h1 className="text-2xl">Dua Page</h1>
              <div className="flex space-x-4 items-center">
                <SeachBar />
                <Avatar />
                <Drawar />
              </div>
            </div>
            <div className="flex gap-8">
              <div className="w-[66%] hidden lg:block">
                <CategoryNav data={categorys} />
              </div>
              <div className=" flex-grow mt-4">{children}</div>
            </div>
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
